/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SafetyTipsRouteImport } from './routes/safety-tips'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PriceEstimatorRouteImport } from './routes/price-estimator'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DealersRouteImport } from './routes/dealers'
import { Route as DealerSignupRouteImport } from './routes/dealer-signup'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as DealersSlugRouteImport } from './routes/dealers.$slug'
import { Route as DashboardOffersRouteImport } from './routes/dashboard.offers'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ListingsIdEditRouteImport } from './routes/listings.$id.edit'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyTipsRoute = SafetyTipsRouteImport.update({
  id: '/safety-tips',
  path: '/safety-tips',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceEstimatorRoute = PriceEstimatorRouteImport.update({
  id: '/price-estimator',
  path: '/price-estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersRoute = DealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerSignupRoute = DealerSignupRouteImport.update({
  id: '/dealer-signup',
  path: '/dealer-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersSlugRoute = DealersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DealersRoute,
} as any)
const DashboardOffersRoute = DashboardOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ListingsIdEditRoute = ListingsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ListingsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/browse': typeof BrowseRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dealer-signup': typeof DealerSignupRoute
  '/dealers': typeof DealersRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/price-estimator': typeof PriceEstimatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/saved': typeof SavedRoute
  '/sell': typeof SellRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dealers/$slug': typeof DealersSlugRoute
  '/listings/$id': typeof ListingsIdRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dealer-signup': typeof DealerSignupRoute
  '/dealers': typeof DealersRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/price-estimator': typeof PriceEstimatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/saved': typeof SavedRoute
  '/sell': typeof SellRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dealers/$slug': typeof DealersSlugRoute
  '/listings/$id': typeof ListingsIdRouteWithChildren
  '/blog': typeof BlogIndexRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/browse': typeof BrowseRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dealer-signup': typeof DealerSignupRoute
  '/dealers': typeof DealersRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/price-estimator': typeof PriceEstimatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/saved': typeof SavedRoute
  '/sell': typeof SellRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dealers/$slug': typeof DealersSlugRoute
  '/listings/$id': typeof ListingsIdRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/browse'
    | '/compare'
    | '/dashboard'
    | '/dealer-signup'
    | '/dealers'
    | '/notifications'
    | '/price-estimator'
    | '/privacy-policy'
    | '/safety-tips'
    | '/saved'
    | '/sell'
    | '/terms-of-service'
    | '/auth/callback'
    | '/blog/$slug'
    | '/dashboard/offers'
    | '/dealers/$slug'
    | '/listings/$id'
    | '/blog/'
    | '/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/compare'
    | '/dashboard'
    | '/dealer-signup'
    | '/dealers'
    | '/notifications'
    | '/price-estimator'
    | '/privacy-policy'
    | '/safety-tips'
    | '/saved'
    | '/sell'
    | '/terms-of-service'
    | '/auth/callback'
    | '/blog/$slug'
    | '/dashboard/offers'
    | '/dealers/$slug'
    | '/listings/$id'
    | '/blog'
    | '/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/browse'
    | '/compare'
    | '/dashboard'
    | '/dealer-signup'
    | '/dealers'
    | '/notifications'
    | '/price-estimator'
    | '/privacy-policy'
    | '/safety-tips'
    | '/saved'
    | '/sell'
    | '/terms-of-service'
    | '/auth/callback'
    | '/blog/$slug'
    | '/dashboard/offers'
    | '/dealers/$slug'
    | '/listings/$id'
    | '/blog/'
    | '/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DealerSignupRoute: typeof DealerSignupRoute
  DealersRoute: typeof DealersRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PriceEstimatorRoute: typeof PriceEstimatorRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SafetyTipsRoute: typeof SafetyTipsRoute
  SavedRoute: typeof SavedRoute
  SellRoute: typeof SellRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ListingsIdRoute: typeof ListingsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-tips': {
      id: '/safety-tips'
      path: '/safety-tips'
      fullPath: '/safety-tips'
      preLoaderRoute: typeof SafetyTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-estimator': {
      id: '/price-estimator'
      path: '/price-estimator'
      fullPath: '/price-estimator'
      preLoaderRoute: typeof PriceEstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers': {
      id: '/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof DealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer-signup': {
      id: '/dealer-signup'
      path: '/dealer-signup'
      fullPath: '/dealer-signup'
      preLoaderRoute: typeof DealerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers/$slug': {
      id: '/dealers/$slug'
      path: '/$slug'
      fullPath: '/dealers/$slug'
      preLoaderRoute: typeof DealersSlugRouteImport
      parentRoute: typeof DealersRoute
    }
    '/dashboard/offers': {
      id: '/dashboard/offers'
      path: '/offers'
      fullPath: '/dashboard/offers'
      preLoaderRoute: typeof DashboardOffersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/listings/$id/edit': {
      id: '/listings/$id/edit'
      path: '/edit'
      fullPath: '/listings/$id/edit'
      preLoaderRoute: typeof ListingsIdEditRouteImport
      parentRoute: typeof ListingsIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DashboardRouteChildren {
  DashboardOffersRoute: typeof DashboardOffersRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOffersRoute: DashboardOffersRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DealersRouteChildren {
  DealersSlugRoute: typeof DealersSlugRoute
}

const DealersRouteChildren: DealersRouteChildren = {
  DealersSlugRoute: DealersSlugRoute,
}

const DealersRouteWithChildren =
  DealersRoute._addFileChildren(DealersRouteChildren)

interface ListingsIdRouteChildren {
  ListingsIdEditRoute: typeof ListingsIdEditRoute
}

const ListingsIdRouteChildren: ListingsIdRouteChildren = {
  ListingsIdEditRoute: ListingsIdEditRoute,
}

const ListingsIdRouteWithChildren = ListingsIdRoute._addFileChildren(
  ListingsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  BrowseRoute: BrowseRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DealerSignupRoute: DealerSignupRoute,
  DealersRoute: DealersRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PriceEstimatorRoute: PriceEstimatorRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SafetyTipsRoute: SafetyTipsRoute,
  SavedRoute: SavedRoute,
  SellRoute: SellRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ListingsIdRoute: ListingsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
